version: "3"
services:
  mysql:　
    build:
      context: ./mysql/
      dockerfile: Dockerfile
    volumes:
      - ./mysql/initdb.d:/docker-entrypoint-initdb.d
    environment:
      - MYSQL_ROOT_PASSWORD=root
    expose:
      - 3306

